services:
  - type: web
    name: wordly-mailer
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: GMAIL_USER
        sync: false   # set in Render dashboard
      - key: GMAIL_PASS
        sync: false   # set in Render dashboard
