package com.example.nuraienglish.feature.cards

import com.example.nuraienglish.core.data.model.AppLanguage

data class CardStudyStrings(
    val studyCards: String,
    val practiceTasks: String,
    val cardsTitle: String,
    val noCards: String,
    val cardOf: String,
    val tapToReveal: String,
    val tapToHide: String,
    val translation: String,
    val correctForm: String,
    val englishSentence: String,
    val listenFirst: String,
    val reveal: String,
    val previous: String,
    val next: String,
    val startPractice: String,
    val cardsComplete: String,
    val reviewAgain: String,
    val wordCard: String,
    val sentenceCard: String,
    val grammarCard: String,
    val listeningCard: String,
    val phraseCard: String,
    val note: String,
    val addCard: String,
    val newCard: String,
    val editCard: String,
    val saveCard: String,
    val cardType: String,
    val front: String,
    val back: String,
    val speakText: String,
    val wordNote: String,
    val sentenceNote: String,
    val grammarNote: String,
    val listeningNote: String,
    val wordsToUse: String,
)

fun AppLanguage.cardStudyStrings(): CardStudyStrings = when (this) {
    AppLanguage.RUSSIAN -> CardStudyStrings(
        studyCards = "Карточки",
        practiceTasks = "Задачи",
        cardsTitle = "Карточки урока",
        noCards = "Для этого урока пока нет карточек.",
        cardOf = "из",
        tapToReveal = "Нажмите, чтобы открыть ответ",
        tapToHide = "Нажмите, чтобы снова скрыть",
        translation = "Перевод",
        correctForm = "Правильная форма",
        englishSentence = "Английское предложение",
        listenFirst = "Сначала послушайте, потом откройте карточку",
        reveal = "Показать",
        previous = "Назад",
        next = "Далее",
        startPractice = "Перейти к задачам",
        cardsComplete = "Карточки изучены",
        reviewAgain = "Повторить карточки",
        wordCard = "Новое слово",
        sentenceCard = "Фраза",
        grammarCard = "Грамматика",
        listeningCard = "Аудирование",
        phraseCard = "Полезная фраза",
        note = "Подсказка",
        addCard = "Добавить карточку",
        newCard = "Новая карточка",
        editCard = "Редактировать карточку",
        saveCard = "Сохранить карточку",
        cardType = "Тип карточки",
        front = "Лицевая сторона",
        back = "Обратная сторона",
        speakText = "Текст для озвучки",
        wordNote = "Произнесите слово вслух и свяжите его с переводом.",
        sentenceNote = "Сначала поймите смысл, затем попробуйте сказать по-английски.",
        grammarNote = "Обратите внимание на форму: она важнее дословного перевода.",
        listeningNote = "Повторите за аудио и проверьте смысл после открытия карточки.",
        wordsToUse = "Слова для сборки",
    )
    AppLanguage.KAZAKH -> CardStudyStrings(
        studyCards = "Карточкалар",
        practiceTasks = "Тапсырмалар",
        cardsTitle = "Сабақ карточкалары",
        noCards = "Бұл сабақта әзірге карточкалар жоқ.",
        cardOf = "/",
        tapToReveal = "Жауапты ашу үшін басыңыз",
        tapToHide = "Қайта жасыру үшін басыңыз",
        translation = "Аударма",
        correctForm = "Дұрыс форма",
        englishSentence = "Ағылшынша сөйлем",
        listenFirst = "Алдымен тыңдаңыз, содан кейін карточканы ашыңыз",
        reveal = "Көрсету",
        previous = "Артқа",
        next = "Келесі",
        startPractice = "Тапсырмаларға өту",
        cardsComplete = "Карточкалар оқылды",
        reviewAgain = "Карточкаларды қайталау",
        wordCard = "Жаңа сөз",
        sentenceCard = "Сөйлем",
        grammarCard = "Грамматика",
        listeningCard = "Тыңдау",
        phraseCard = "Пайдалы тіркес",
        note = "Кеңес",
        addCard = "Карточка қосу",
        newCard = "Жаңа карточка",
        editCard = "Карточканы өңдеу",
        saveCard = "Карточканы сақтау",
        cardType = "Карточка түрі",
        front = "Алдыңғы беті",
        back = "Артқы беті",
        speakText = "Дыбыстау мәтіні",
        wordNote = "Сөзді дауыстап айтып, аудармасымен байланыстырыңыз.",
        sentenceNote = "Алдымен мағынасын түсініп, кейін ағылшынша айтып көріңіз.",
        grammarNote = "Формаға назар аударыңыз: ол сөзбе-сөз аудармадан маңызды.",
        listeningNote = "Аудиодан кейін қайталап, карточканы ашқанда мағынасын тексеріңіз.",
        wordsToUse = "Құрастыруға арналған сөздер",
    )
    else -> CardStudyStrings(
        studyCards = "Cards",
        practiceTasks = "Tasks",
        cardsTitle = "Lesson Cards",
        noCards = "No cards in this lesson yet.",
        cardOf = "of",
        tapToReveal = "Tap to reveal the answer",
        tapToHide = "Tap to hide again",
        translation = "Translation",
        correctForm = "Correct form",
        englishSentence = "English sentence",
        listenFirst = "Listen first, then reveal the card",
        reveal = "Reveal",
        previous = "Previous",
        next = "Next",
        startPractice = "Start tasks",
        cardsComplete = "Cards complete",
        reviewAgain = "Review cards again",
        wordCard = "New word",
        sentenceCard = "Sentence",
        grammarCard = "Grammar",
        listeningCard = "Listening",
        phraseCard = "Useful phrase",
        note = "Note",
        addCard = "Add Card",
        newCard = "New Card",
        editCard = "Edit Card",
        saveCard = "Save Card",
        cardType = "Card type",
        front = "Front",
        back = "Back",
        speakText = "Speech text",
        wordNote = "Say the word aloud and connect it with the translation.",
        sentenceNote = "Understand the meaning first, then try saying it in English.",
        grammarNote = "Notice the form: here the pattern matters more than word-for-word translation.",
        listeningNote = "Repeat after the audio and check the meaning after revealing the card.",
        wordsToUse = "Words to use",
    )
}
