package com.example.nuraienglish.core.ui

import com.example.nuraienglish.core.data.model.AppLanguage

data class UiStrings(
    // Home
    val myProgress: String,
    val review: String,
    val courses: String,
    val seeAll: String,
    val noCoursesYet: String,
    val adminPanel: String,
    val hello: String,
    val pointsEarned: String,
    // Course list
    val allCourses: String,
    val noCoursesAvailable: String,
    // Lesson list
    val noLessonsAvailable: String,
    val lessons: String,
    val lessonsDone: String,
    val lessonsOf: String,
    // Lesson card
    val tasks: String,
    val pts: String,
    // Language dialog
    val interfaceLanguage: String,
    val close: String,
    // Course type chip labels
    val typeVocabulary: String,
    val typeGrammar: String,
    val typeListening: String,
    // Task screen
    val noTasks: String,
    val taskWord: String,
    val translateWord: String,
    val translateSentence: String,
    val yourAnswer: String,
    val correctPrefix: String,
    val check: String,
    val chooseCorrect: String,
    val buildSentence: String,
    val tapWords: String,
    val clear: String,
    val correctContinue: String,
    val wrongNext: String,
    val lessonComplete: String,
    val youEarnedPoints: String,
    val correctCount: String,
    val outOf: String,
    val notEnoughForPoints: String,
    val backToHome: String,
    // Review screen
    val reviewTitle: String,
    val reviewComplete: String,
    val noMoreMistakes: String,
    val mistakeLabel: String,
    // Auth screens
    val signIn: String,
    val signUp: String,
    val learnEveryDay: String,
    val emailLabel: String,
    val passwordLabel: String,
    val yourNameLabel: String,
    val confirmPasswordLabel: String,
    val createAccount: String,
    val createAccountSubtitle: String,
    val noAccount: String,
    val hasAccount: String,
    val errorFillAllFields: String,
    val errorEnterEmail: String,
    val errorEnterName: String,
    val errorPasswordTooShort: String,
    val errorPasswordMismatch: String,
    // Listening task types
    val listenAndTranslate: String,
    val listenAndWrite: String,
    val tapToListenHint: String,
    val typeWhatYouHear: String,
    // Firebase auth errors
    val errorEmailInUse: String,
    val errorWrongCredentials: String,
    val errorInvalidEmail: String,
    val errorWeakPassword: String,
    val errorTooManyRequests: String,
    val errorNetwork: String,
    val errorUserDisabled: String,
    val errorUnknown: String,
)

fun AppLanguage.uiStrings(): UiStrings = when (this) {
    AppLanguage.RUSSIAN -> UiStrings(
        myProgress        = "Мой прогресс",
        review            = "Повторение",
        courses           = "Курсы",
        seeAll            = "Все",
        noCoursesYet      = "Курсов пока нет. Загляните позже!",
        adminPanel        = "Панель администратора",
        hello             = "Привет",
        pointsEarned      = "очков набрано",
        allCourses        = "Все курсы",
        noCoursesAvailable = "Курсов пока нет.",
        noLessonsAvailable = "Уроков пока нет.",
        lessons           = "уроков",
        lessonsDone       = "уроков пройдено",
        lessonsOf         = "из",
        tasks             = "заданий",
        pts               = "очков",
        interfaceLanguage = "Язык интерфейса",
        close             = "Закрыть",
        typeVocabulary    = "Словарный запас",
        typeGrammar       = "Грамматика",
        typeListening     = "Аудирование",
        noTasks           = "В этом уроке пока нет заданий.",
        taskWord          = "Задание",
        translateWord     = "Переведите слово",
        translateSentence = "Переведите предложение",
        yourAnswer        = "Ваш ответ",
        correctPrefix     = "Правильно: ",
        check             = "Проверить",
        chooseCorrect     = "Выберите правильный ответ",
        buildSentence     = "Составьте предложение",
        tapWords          = "Нажимайте слова, чтобы составить предложение",
        clear             = "Очистить",
        correctContinue   = "Правильно! Далее",
        wrongNext         = "Неправильно — Далее",
        lessonComplete    = "Урок завершён!",
        youEarnedPoints   = "Вы заработали очки за этот урок.",
        correctCount      = "правильных",
        outOf             = "из",
        notEnoughForPoints = "Нужно 80% правильных ответов для получения очков",
        backToHome        = "На главную",
        reviewTitle       = "Работа над ошибками",
        reviewComplete    = "Повторение завершено!",
        noMoreMistakes    = "Ошибок для повторения больше нет.",
        mistakeLabel      = "Ошибка",
        listenAndTranslate = "Послушайте и переведите",
        listenAndWrite    = "Послушайте и напишите",
        tapToListenHint   = "Нажмите, чтобы послушать снова",
        typeWhatYouHear   = "Напишите то, что слышите",
        signIn            = "Войти",
        signUp            = "Зарегистрироваться",
        learnEveryDay     = "Учи английский каждый день",
        emailLabel        = "Электронная почта",
        passwordLabel     = "Пароль",
        yourNameLabel     = "Ваше имя",
        confirmPasswordLabel = "Подтвердите пароль",
        createAccount     = "Создать аккаунт",
        createAccountSubtitle = "Заполните данные для начала",
        noAccount         = "Нет аккаунта? Зарегистрируйтесь",
        hasAccount        = "Уже есть аккаунт? Войдите",
        errorFillAllFields    = "Пожалуйста, заполните все поля",
        errorEnterEmail       = "Введите адрес электронной почты",
        errorEnterName        = "Введите ваше имя",
        errorPasswordTooShort = "Пароль должен содержать не менее 6 символов",
        errorPasswordMismatch = "Пароли не совпадают",
        errorEmailInUse       = "Этот email уже используется другим аккаунтом",
        errorWrongCredentials = "Неверный email или пароль",
        errorInvalidEmail     = "Некорректный адрес электронной почты",
        errorWeakPassword     = "Пароль слишком простой. Используйте не менее 6 символов",
        errorTooManyRequests  = "Слишком много попыток. Попробуйте позже",
        errorNetwork          = "Ошибка сети. Проверьте подключение к интернету",
        errorUserDisabled     = "Этот аккаунт заблокирован. Обратитесь в поддержку",
        errorUnknown          = "Произошла ошибка. Попробуйте ещё раз",
    )
    AppLanguage.KAZAKH -> UiStrings(
        myProgress        = "Менің прогресім",
        review            = "Қайталау",
        courses           = "Курстар",
        seeAll            = "Барлығы",
        noCoursesYet      = "Курстар әлі жоқ. Кейінірек қараңыз!",
        adminPanel        = "Әкімші панелі",
        hello             = "Сәлем",
        pointsEarned      = "ұпай жиналды",
        allCourses        = "Барлық курстар",
        noCoursesAvailable = "Курстар әлі жоқ.",
        noLessonsAvailable = "Сабақтар әлі жоқ.",
        lessons           = "сабақ",
        lessonsDone       = "сабақ өтілді",
        lessonsOf         = "/",
        tasks             = "тапсырма",
        pts               = "ұпай",
        interfaceLanguage = "Интерфейс тілі",
        close             = "Жабу",
        typeVocabulary    = "Сөздік қор",
        typeGrammar       = "Грамматика",
        typeListening     = "Тыңдау",
        noTasks           = "Бұл сабақта тапсырма жоқ.",
        taskWord          = "Тапсырма",
        translateWord     = "Сөзді аударыңыз",
        translateSentence = "Сөйлемді аударыңыз",
        yourAnswer        = "Сіздің жауабыңыз",
        correctPrefix     = "Дұрыс: ",
        check             = "Тексеру",
        chooseCorrect     = "Дұрыс жауапты таңдаңыз",
        buildSentence     = "Сөйлем құраңыз",
        tapWords          = "Сөйлем құру үшін сөздерді басыңыз",
        clear             = "Тазалау",
        correctContinue   = "Дұрыс! Жалғастыру",
        wrongNext         = "Қате — Келесі",
        lessonComplete    = "Сабақ аяқталды!",
        youEarnedPoints   = "Сіз сабақ үшін ұпай жинадыңыз.",
        correctCount      = "дұрыс",
        outOf             = "/",
        notEnoughForPoints = "Ұпай алу үшін 80% дұрыс жауап қажет",
        backToHome        = "Басты бетке",
        reviewTitle       = "Қателер үстінде жұмыс",
        reviewComplete    = "Қайталау аяқталды!",
        noMoreMistakes    = "Қайталайтын қателер жоқ.",
        mistakeLabel      = "Қате",
        listenAndTranslate = "Тыңдап аударыңыз",
        listenAndWrite    = "Тыңдап жазыңыз",
        tapToListenHint   = "Қайта тыңдау үшін басыңыз",
        typeWhatYouHear   = "Естігеніңізді жазыңыз",
        signIn            = "Кіру",
        signUp            = "Тіркелу",
        learnEveryDay     = "Ағылшынша күнде үйрен",
        emailLabel        = "Электрондық пошта",
        passwordLabel     = "Құпия сөз",
        yourNameLabel     = "Сіздің атыңыз",
        confirmPasswordLabel = "Құпия сөзді растаңыз",
        createAccount     = "Аккаунт жасау",
        createAccountSubtitle = "Бастау үшін деректерді толтырыңыз",
        noAccount         = "Аккаунт жоқ па? Тіркелу",
        hasAccount        = "Аккаунт бар ма? Кіру",
        errorFillAllFields    = "Барлық өрістерді толтырыңыз",
        errorEnterEmail       = "Электрондық пошта мекенжайын енгізіңіз",
        errorEnterName        = "Атыңызды енгізіңіз",
        errorPasswordTooShort = "Құпия сөз кемінде 6 таңбадан тұруы керек",
        errorPasswordMismatch = "Құпия сөздер сәйкес келмейді",
        errorEmailInUse       = "Бұл email басқа аккаунтта пайдаланылып жатыр",
        errorWrongCredentials = "Қате email немесе құпия сөз",
        errorInvalidEmail     = "Электрондық пошта мекенжайы дұрыс емес",
        errorWeakPassword     = "Құпия сөз тым қарапайым. Кемінде 6 таңба пайдаланыңыз",
        errorTooManyRequests  = "Тым көп әрекет. Кейінірек қайталап көріңіз",
        errorNetwork          = "Желі қатесі. Интернет байланысын тексеріңіз",
        errorUserDisabled     = "Бұл аккаунт бұғатталған. Қолдау қызметіне хабарласыңыз",
        errorUnknown          = "Қате орын алды. Қайталап көріңіз",
    )
    else -> UiStrings(
        myProgress        = "My Progress",
        review            = "Review",
        courses           = "Courses",
        seeAll            = "See all",
        noCoursesYet      = "No courses yet. Check back soon!",
        adminPanel        = "Admin Panel",
        hello             = "Hello",
        pointsEarned      = "points earned",
        allCourses        = "All Courses",
        noCoursesAvailable = "No courses available yet.",
        noLessonsAvailable = "No lessons available yet.",
        lessons           = "lessons",
        lessonsDone       = "lessons done",
        lessonsOf         = "of",
        tasks             = "tasks",
        pts               = "pts",
        interfaceLanguage = "Interface Language",
        close             = "Close",
        typeVocabulary    = "Vocabulary",
        typeGrammar       = "Grammar",
        typeListening     = "Listening",
        noTasks           = "No tasks in this lesson yet.",
        taskWord          = "Task",
        translateWord     = "Translate this word",
        translateSentence = "Translate this sentence",
        yourAnswer        = "Your answer",
        correctPrefix     = "Correct: ",
        check             = "Check",
        chooseCorrect     = "Choose the correct answer",
        buildSentence     = "Build the sentence",
        tapWords          = "Tap words below to build the sentence",
        clear             = "Clear",
        correctContinue   = "Correct! Continue",
        wrongNext         = "Wrong — Next",
        lessonComplete    = "Lesson Complete!",
        youEarnedPoints   = "You earned points for finishing this lesson.",
        correctCount      = "correct",
        outOf             = "of",
        notEnoughForPoints = "Need 80% correct answers to earn points",
        backToHome        = "Back to Home",
        reviewTitle       = "Review Mistakes",
        reviewComplete    = "Review Complete!",
        noMoreMistakes    = "No more mistakes to review right now.",
        mistakeLabel      = "Mistake",
        listenAndTranslate = "Listen and translate",
        listenAndWrite    = "Listen and write it down",
        tapToListenHint   = "Tap to listen again",
        typeWhatYouHear   = "Type what you hear",
        signIn            = "Sign In",
        signUp            = "Sign Up",
        learnEveryDay     = "Learn English every day",
        emailLabel        = "Email",
        passwordLabel     = "Password",
        yourNameLabel     = "Your name",
        confirmPasswordLabel = "Confirm password",
        createAccount     = "Create Account",
        createAccountSubtitle = "Fill in your details to get started",
        noAccount         = "Don't have an account? Sign up",
        hasAccount        = "Already have an account? Sign in",
        errorFillAllFields    = "Please fill in all fields",
        errorEnterEmail       = "Enter your email address",
        errorEnterName        = "Enter your name",
        errorPasswordTooShort = "Password must be at least 6 characters",
        errorPasswordMismatch = "Passwords do not match",
        errorEmailInUse       = "This email is already used by another account",
        errorWrongCredentials = "Incorrect email or password",
        errorInvalidEmail     = "Invalid email address",
        errorWeakPassword     = "Password is too weak. Use at least 6 characters",
        errorTooManyRequests  = "Too many attempts. Please try again later",
        errorNetwork          = "Network error. Check your internet connection",
        errorUserDisabled     = "This account has been disabled. Contact support",
        errorUnknown          = "Something went wrong. Please try again",
    )
}
